const tabs=['Dashboard','Matchcenter','Livecenter','Scout Center','Resecenter','Media','Familj','Push','AI','Admin'];
const state={notes:JSON.parse(localStorage.getItem('mh_notes')||'[]'),stats:JSON.parse(localStorage.getItem('mh_stats')||'{"gp":0,"g":0,"a":0,"pim":0,"pm":0}'),prefs:JSON.parse(localStorage.getItem('mh_prefs')||'{"budget":10000,"departAfter":"09:30"}')};
const schedule=[
{date:'2026-09-18',time:'19:00',opponent:'Blackfalds Bulldogs',home:false,arena:'Eagle Builders Centre',scout:'Säsongsstart',sv:'2026-09-19 03:00'},
{date:'2026-09-19',time:'19:00',opponent:'Okotoks Oilers',home:true,arena:'Centennial Regional Arena',scout:'Rivalmatch',sv:'2026-09-20 03:00'},
{date:'2026-09-25',time:'19:00',opponent:'Spruce Grove Saints',home:true,arena:'Centennial Regional Arena',scout:'Divisionsmatch',sv:'2026-09-26 03:00'}
];
function save(){localStorage.setItem('mh_notes',JSON.stringify(state.notes));localStorage.setItem('mh_stats',JSON.stringify(state.stats));localStorage.setItem('mh_prefs',JSON.stringify(state.prefs));}
function nextMatch(){return schedule[0]}
function shell(){document.querySelector('#app').innerHTML=`<header><div class="brand"><div class="logo">MH</div><div><b>MansHockey Pro X</b><div class="small">Måns Ågren • Brooks Bandits • Family Command Center</div></div></div><button onclick="installApp()">Installera app</button></header><nav class="tabs">${tabs.map(t=>`<button class="tab" data-tab="${t}" onclick="render('${t}')">${t}</button>`).join('')}</nav><main id="view"></main>`;render('Dashboard'); if('serviceWorker'in navigator) navigator.serviceWorker.register('/service-worker.js').catch(()=>{});}
window.installApp=()=>alert('På iPhone: öppna manshockey.com i Safari → Dela → Lägg till på hemskärmen. På Android/Chrome visas ofta Installera automatiskt.');
function activate(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
window.render=function(tab){activate(tab); const v=document.querySelector('#view'); const m=nextMatch();
if(tab==='Dashboard') v.innerHTML=`<section class="hero"><div class="big"><h1>Nästa match: Brooks ${m.home?'vs':'@'} ${m.opponent}</h1><div class="countdown" id="countdown">Laddar...</div><div class="kpi"><span class="pill">🇸🇪 ${m.sv}</span><span class="pill">📍 ${m.arena}</span><span class="pill">⭐ ${m.scout}</span><span class="pill">📺 FloHockey</span></div><p>Snabböversikt för familjen: match, resor, media, statistik och egna anteckningar.</p></div><div class="card"><h2>Måns snabbstatistik</h2>${statsHtml()}<button onclick="render('Scout Center')">Öppna Scout Center</button></div></section><section class="grid"><div class="card"><h3>✈️ Flyg</h3><p>ARN–YYC, Air Canada/KLM/Finnair. Ingen USA-transit, avgång efter ${state.prefs.departAfter}, max ${state.prefs.budget} kr.</p><button onclick="render('Resecenter')">Sök flyg</button></div><div class="card"><h3>📰 Media</h3><p>Bevakar Måns Ågren, Mans Agren, Brooks Bandits och BCHL.</p><button onclick="render('Media')">Öppna media</button></div><div class="card"><h3>🤖 AI</h3><p>Skapa inför- och efterrapporter, reseförslag och mediasammanfattningar.</p><button onclick="render('AI')">Öppna AI</button></div><div class="card wide"><h3>Kommande matcher</h3>${matchList()}</div><div class="card"><h3>Familj</h3><p>Anteckningar, packlistor, pass/visum, försäkring och reseplanering.</p><button onclick="render('Familj')">Öppna familjedel</button></div></section>`; tick();
if(tab==='Matchcenter') v.innerHTML=`<section class="grid"><div class="card full"><h1>🏒 Matchcenter</h1><p>Varje match har inför-rapport, efterrapport, länkar, anteckningar och Måns statistik.</p></div>${schedule.map((x,i)=>`<div class="card"><h2>${x.home?'Brooks vs':'Brooks @'} ${x.opponent}</h2><p>${x.sv} svensk tid<br>${x.arena}</p><span class="tag gold">${x.scout}</span><h3>Inför match</h3><p>${preReport(x)}</p><h3>Efter match</h3><textarea placeholder="Fyll i resultat, Måns statistik, highlights och egna observationer"></textarea><button onclick="addNote('Match ${i+1}: ${x.opponent}')">Spara matchanteckning</button></div>`).join('')}</section>`;
if(tab==='Livecenter') v.innerHTML=`<section class="grid"><div class="card full"><h1>📊 Livecenter</h1><p>Plats för BCHL-tabell, resultat, formkurvor och lagstatistik. Livekoppling kan läggas på API när datakälla är vald.</p></div><div class="card"><h3>BCHL-tabell</h3><div class="row"><b>Brooks Bandits</b><span class="tag green">0 p</span></div><div class="row"><b>Okotoks Oilers</b><span>0 p</span></div><div class="row"><b>Spruce Grove Saints</b><span>0 p</span></div></div><div class="card wide"><h3>Resultatflöde</h3><p>Här visas automatiskt senaste resultat när BCHL-källa kopplas.</p>${matchList()}</div></section>`;
if(tab==='Scout Center') v.innerHTML=`<section class="grid"><div class="card full"><h1>⭐ Scout Center</h1><p>Följ Måns utveckling, skriv scoutlogg och exportera underlag.</p></div><div class="card"><h3>Statistik</h3>${statsHtml()}${['gp','g','a','pim','pm'].map(k=>`<label>${k.toUpperCase()}<input type="number" value="${state.stats[k]}" onchange="state.stats.${k}=+this.value;save();render('Scout Center')"></label>`).join('')}</div><div class="card wide"><h3>Scoutlogg</h3><textarea id="scoutNote" placeholder="Ex: stark boxplay, bra gap control, förstapass..."></textarea><button onclick="addNote(document.getElementById('scoutNote').value||'Scoutanteckning')">Spara logg</button><div class="list">${state.notes.map(n=>`<div class="row"><span>${n}</span><span class="tag">sparad</span></div>`).join('')}</div></div><div class="card full"><h3>Export</h3><button onclick="window.print()">Skriv ut / spara som PDF</button></div></section>`;
if(tab==='Resecenter') v.innerHTML=`<section class="grid"><div class="card full"><h1>✈️ Resecenter</h1><p>Sök och bevaka ARN–Calgary med Air Canada, KLM och Finnair.</p></div><div class="card"><label>Datum<input type="date" id="flightDate"></label><label>Maxpris SEK<input type="number" value="${state.prefs.budget}" onchange="state.prefs.budget=+this.value;save()"></label><label>Avgång efter<input value="${state.prefs.departAfter}" onchange="state.prefs.departAfter=this.value;save()"></label><button onclick="flightSearch()">Sök/bevaka</button><div id="flightResult"></div></div><div class="card wide"><h3>Regler</h3><div class="row"><b>Flygbolag</b><span>Air Canada, KLM, Finnair</span></div><div class="row"><b>Rutt</b><span>ARN → YYC</span></div><div class="row"><b>Filter</b><span>Ingen USA-transit, kort restid, efter 09:30</span></div><p class="small">För livepriser kopplas Amadeus/Skyscanner/Kiwi API i Cloudflare Functions.</p></div></section>`;
if(tab==='Media') v.innerHTML=`<section class="grid"><div class="card full"><h1>📰 Media Watch</h1><p>Regelbunden bevakning av Måns Ågren och relaterade sökord.</p></div><div class="card"><button onclick="mediaSearch()">Kolla nu</button><div id="mediaResult"></div></div><div class="card wide"><h3>Sökknappar</h3>${['Måns Ågren','Mans Agren','Brooks Bandits Agren','BCHL Måns Ågren','EliteProspects Måns Ågren'].map(q=>`<a class="pill" target="_blank" href="https://www.google.com/search?q=${encodeURIComponent(q)}">${q}</a>`).join(' ')}</div></section>`;
if(tab==='Familj') v.innerHTML=`<section class="grid"><div class="card full"><h1>👨‍👩‍👧 Familjeportal</h1></div><div class="card"><h3>Packlista Kanada</h3>${['Pass/eTA','Försäkring','Klubbkontakt','Laddare','Varma kläder','Matchtröja'].map(x=>`<div class="row"><span>${x}</span><input type="checkbox" style="width:auto"></div>`).join('')}</div><div class="card"><h3>Dokument</h3><p>Här kan ni lägga länkar till pass, försäkring, visum/eTA, BCHL-info och resehandlingar.</p><textarea placeholder="Klistra in länkar/anteckningar"></textarea></div><div class="card wide"><h3>Familjeanteckningar</h3><textarea id="famNote"></textarea><button onclick="addNote(document.getElementById('famNote').value||'Familjeanteckning')">Spara</button>${state.notes.map(n=>`<div class="row"><span>${n}</span></div>`).join('')}</div></section>`;
if(tab==='Push') v.innerHTML=`<section class="grid"><div class="card full"><h1>🔔 Pushnotiser</h1><p>Förberedda notifieringar. Riktiga pushnotiser kräver web push-nycklar och Cloudflare Worker/Queue.</p></div>${['Match om 60 minuter','Ny artikel om Måns','Flyg under budget','Matchrapport klar','Ny statistik'].map(x=>`<div class="card"><h3>${x}</h3><button onclick="alert('Demo-notis: ${x}')">Testa</button></div>`).join('')}</section>`;
if(tab==='AI') v.innerHTML=`<section class="grid"><div class="card full"><h1>🤖 AI-assistent</h1><p>Ställ frågor om match, flyg, media och scoutlogg. Demo lokalt – kan kopplas till AI API senare.</p></div><div class="card wide"><textarea id="aiq" placeholder="Ex: Skriv en inför-rapport mot Okotoks"></textarea><button onclick="aiAnswer()">Svara</button><div id="aiout"></div></div><div class="card"><h3>Snabbkommandon</h3>${['Inför match','Efter match','Flygförslag','Mediasammanfattning','Scout-PDF'].map(x=>`<button onclick="document.getElementById('aiq').value='${x}';aiAnswer()">${x}</button>`).join('')}</div></section>`;
if(tab==='Admin') v.innerHTML=`<section class="grid"><div class="card full"><h1>⚙️ Admin</h1><p>Lokala inställningar och datagrund.</p></div><div class="card"><h3>Inställningar</h3><label>Budget<input type="number" value="${state.prefs.budget}" onchange="state.prefs.budget=+this.value;save()"></label><label>Avgång efter<input value="${state.prefs.departAfter}" onchange="state.prefs.departAfter=this.value;save()"></label><button onclick="localStorage.clear();location.reload()">Nollställ lokal data</button></div><div class="card wide"><h3>Nästa tekniska kopplingar</h3><p>BCHL-datakälla, flyg-API, media-RSS, pushnycklar, inloggning och adminpanel.</p></div></section>`;
};
function statsHtml(){const s=state.stats;return `<div class="statline"><div class="stat"><b>${s.gp}</b><span>GP</span></div><div class="stat"><b>${s.g}</b><span>G</span></div><div class="stat"><b>${s.a}</b><span>A</span></div><div class="stat"><b>${s.g+s.a}</b><span>P</span></div><div class="stat"><b>${s.pm}</b><span>+/-</span></div></div>`}
function matchList(){return `<div class="list">${schedule.map(x=>`<div class="row"><div><b>${x.home?'Hemma':'Borta'}: ${x.opponent}</b><div class="small">${x.sv} • ${x.arena}</div></div><span class="tag ${x.home?'green':'red'}">${x.home?'HOME':'AWAY'}</span></div>`).join('')}</div>`}
function preReport(x){return `Fokus mot ${x.opponent}: defensiva beslut, gap control, första pass, boxplay och fysiskt spel framför mål. Scoutvärde: ${x.scout}.`}
function tick(){const el=document.getElementById('countdown'); if(!el)return; const target=new Date('2026-09-19T03:00:00+02:00'); const d=target-new Date(); if(d<=0){el.textContent='Matchdag';return} const days=Math.floor(d/864e5), hrs=Math.floor(d%864e5/36e5); el.textContent=`${days} dagar ${hrs} timmar`;}
window.addNote=(n)=>{state.notes.unshift(new Date().toLocaleDateString('sv-SE')+' – '+n);save();alert('Sparat')}
window.flightSearch=async()=>{const d=document.getElementById('flightDate')?.value||''; const r=document.getElementById('flightResult'); r.innerHTML='<p>Söker...</p>'; try{const j=await fetch('/api/flights?date='+d).then(r=>r.json()); r.innerHTML=`<p><b>${j.route}</b><br>${j.airlines.join(', ')}<br>${j.note}</p>`}catch(e){r.innerHTML='<p>Kunde inte hämta flygdata ännu.</p>'}}
window.mediaSearch=async()=>{const r=document.getElementById('mediaResult'); r.innerHTML='<p>Söker...</p>'; try{const j=await fetch('/api/media').then(r=>r.json()); r.innerHTML=`<p>Uppdaterad: ${j.updated}</p><div class="list">${j.queries.map(q=>`<div class="row"><span>${q}</span><a class="tag" target="_blank" href="https://www.google.com/search?q=${encodeURIComponent(q)}">Sök</a></div>`).join('')}</div>`}catch(e){r.innerHTML='<p>Kunde inte hämta mediaflöde.</p>'}}
window.aiAnswer=()=>{const q=document.getElementById('aiq').value; document.getElementById('aiout').innerHTML=`<div class="row"><span><b>AI-utkast:</b> ${q||'Fråga'} – bygg vidare med aktuell matchdata, scoutlogg och mediaflöde.</span></div>`}
shell();
