const tabs=["Dashboard","Matchcenter","Livecenter","Scout","Resor","Media","Familj","Dokument","Karta","AI-assistent","Admin"];
const state={match:{date:"2026-09-18T19:00:00-06:00",opponent:"Blackfalds Bulldogs",home:true,arena:"Centennial Regional Arena, Brooks",link:"https://www.bchl.ca/schedule"}, stats:{gp:0,g:0,a:0,p:0,pm:0,pim:0}, media:["Google News: Måns Ågren","EliteProspects profil","Brooks Bandits nyheter","BCHL media"], flights:[{airline:"Air Canada",price:"Bevakas",route:"ARN–YYC",rule:"Ingen USA, efter 09:30"},{airline:"KLM",price:"Bevakas",route:"ARN–AMS–YYC",rule:"Kort restid"},{airline:"Finnair",price:"Bevakas",route:"ARN–HEL–YYC",rule:"Maxbudget"}]};
const $=id=>document.getElementById(id);
function fmt(d,tz){return new Intl.DateTimeFormat('sv-SE',{timeZone:tz,dateStyle:'medium',timeStyle:'short'}).format(d)}
function tick(){const now=new Date();$('brooksTime').textContent='Brooks '+new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Edmonton',hour:'2-digit',minute:'2-digit'}).format(now);$('swedenTime').textContent='Sverige '+new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',hour:'2-digit',minute:'2-digit'}).format(now)}setInterval(tick,1000);tick();
function countdown(){const diff=new Date(state.match.date)-new Date(); if(diff<0)return 'Säsong igång'; const d=Math.floor(diff/864e5), h=Math.floor(diff%864e5/36e5), m=Math.floor(diff%36e5/6e4); return `${d} dagar ${h} tim ${m} min`}
function nav(active='Dashboard'){tabsEl=$('tabs');tabsEl.innerHTML=tabs.map(t=>`<button class="${t===active?'active':''}" onclick="render('${t}')">${t}</button>`).join('')}
function card(title,html,cls='card'){return `<section class="${cls}"><h3>${title}</h3>${html}</section>`}
function render(tab='Dashboard'){nav(tab); const a=$('app'); if(tab==='Dashboard') a.innerHTML=dashboard(); if(tab==='Matchcenter') a.innerHTML=matchcenter(); if(tab==='Livecenter') a.innerHTML=livecenter(); if(tab==='Scout') a.innerHTML=scout(); if(tab==='Resor') a.innerHTML=resor(); if(tab==='Media') a.innerHTML=media(); if(tab==='Familj') a.innerHTML=familj(); if(tab==='Dokument') a.innerHTML=dokument(); if(tab==='Karta') a.innerHTML=karta(); if(tab==='AI-assistent') a.innerHTML=ai(); if(tab==='Admin') a.innerHTML=admin();}
function dashboard(){return `<div class="grid"><section class="hero"><p class="eyebrow">Nästa match</p><h2>Brooks ${state.match.home?'vs':'@'} ${state.match.opponent}</h2><p>${fmt(new Date(state.match.date),'Europe/Stockholm')} svensk tid · ${fmt(new Date(state.match.date),'America/Edmonton')} Alberta</p><div class="statrow"><div class="stat"><b>${countdown()}</b><span>Nedräkning</span></div><div class="stat"><b>${state.stats.p}</b><span>Poäng</span></div><div class="stat"><b>${state.stats.pm}</b><span>+/-</span></div><div class="stat"><b>54</b><span>Grundseriematcher</span></div><div class="stat"><b>Live</b><span>Data redo</span></div></div></section>${card('Snabbstatus',`<div class="list"><div class="item"><span>Väder Brooks</span><span class="tag warn">API redo</span></div><div class="item"><span>CAD/SEK</span><span class="tag warn">API redo</span></div><div class="item"><span>Media Måns Ågren</span><span class="tag ok">Bevakning</span></div><div class="item"><span>Flyg ARN–YYC</span><span class="tag ok">Bevakning</span></div></div>`)}${card('Måns statistik',statsHtml())}${card('Senaste händelser',`<div class="list"><div class="item"><span>Pro X publicerad</span><span>Idag</span></div><div class="item"><span>GitHub + Cloudflare aktiverat</span><span>Klart</span></div><div class="item"><span>manshockey.com live</span><span>Klart</span></div></div>`,'card wide')}</div>`}
function statsHtml(){return `<div class="statrow"><div class="stat"><b>${state.stats.gp}</b><span>GP</span></div><div class="stat"><b>${state.stats.g}</b><span>G</span></div><div class="stat"><b>${state.stats.a}</b><span>A</span></div><div class="stat"><b>${state.stats.p}</b><span>P</span></div><div class="stat"><b>${state.stats.pim}</b><span>PIM</span></div></div>`}
function matchcenter(){return `<div class="grid">${card('Inför match',`<p><b>Brooks ${state.match.home?'vs':'@'} ${state.match.opponent}</b></p><p class="muted">AI-mall: form, nyckelspelare, special teams, målvakt, scoutfokus och vad familjen ska hålla koll på.</p><textarea placeholder="Egna inför-anteckningar"></textarea><a class="btn gold" href="${state.match.link}" target="_blank">BCHL Matchcenter</a><a class="btn" href="https://www.flohockey.tv/" target="_blank">FloHockey</a>`,'card wide')}${card('Efter match',`<input class="input" placeholder="Resultat, t.ex. Brooks 4–2"/><textarea placeholder="Kort matchrapport, Måns insats, highlights, statistik"></textarea><button class="btn gold">Spara matchrapport</button>`)}${card('Matchlista',`<div class="list"><div class="item"><span>18 sep · Blackfalds</span><span class="tag">Premiär</span></div><div class="item"><span>Kommande matcher</span><span class="tag warn">Import från BCHL</span></div></div>`,'card full')}</div>`}
function livecenter(){return `<div class="grid">${card('BCHL-tabell',`<p class="muted">Här kopplas tabell/resultat in när datakälla finns.</p><div class="progress"><div class="bar"></div></div>`)}${card('Resultat',`<div class="list"><div class="item"><span>Senaste resultat</span><span class="tag warn">API redo</span></div><div class="item"><span>Kommande matcher</span><span class="tag ok">Schema finns</span></div></div>`)}${card('Lagform',`<p>Brooks form senaste 10: fylls automatiskt när säsongen startar.</p>`)}</div>`}
function scout(){return `<div class="grid">${card('Scoutlogg',`<div class="two"><input class="input" placeholder="Match"/><select><option>Defensivt spel</option><option>Förstapass</option><option>Fysik</option><option>Pucktransport</option><option>Boxplay</option></select></div><textarea placeholder="Observationer"></textarea><button class="btn gold">Spara scoutnotering</button>`,'card wide')}${card('Utveckling',`<div class="list"><div class="item"><span>Defensiv</span><span>★★★★★</span></div><div class="item"><span>Förstapass</span><span>★★★★☆</span></div><div class="item"><span>Fysik</span><span>★★★★★</span></div></div>`)}${card('Export',`<p>Skapa PDF-underlag för agent, klubb eller universitet.</p><button class="btn">Exportera säsongsrapport</button>`)}</div>`}
function resor(){return `<div class="grid">${card('Flygsök ARN–YYC',`<div class="two"><input class="input" value="Arlanda ARN"/><input class="input" value="Calgary YYC"/></div><div class="two"><input class="input" type="date"/><input class="input" placeholder="Maxpris SEK"/></div><label><input type="checkbox" checked> Air Canada</label><br><label><input type="checkbox" checked> KLM</label><br><label><input type="checkbox" checked> Finnair</label><br><label><input type="checkbox" checked> Undvik USA-transit</label><br><label><input type="checkbox" checked> Avgång efter 09:30</label><br><button class="btn gold">Sök/bevaka</button>`,'card wide')}${card('Bevakningar',`<div class="list">${state.flights.map(f=>`<div class="item"><span>${f.airline}<br><small class="muted">${f.route} · ${f.rule}</small></span><span class="tag ok">${f.price}</span></div>`).join('')}</div>`)}${card('Reseplan',`<div class="list"><div class="item"><span>Calgary → Brooks</span><span>ca 2 h</span></div><div class="item"><span>Hotell/Bil</span><span class="tag warn">lägg till</span></div></div>`)}</div>`}
function media(){return `<div class="grid">${card('Mediabevakning',`<p>Sökningar: “Måns Ågren”, “Mans Agren”, “Brooks Bandits Måns”, “BCHL Måns Ågren”.</p><a class="btn gold" href="https://www.google.com/search?q=%22M%C3%A5ns+%C3%85gren%22&tbm=nws" target="_blank">Google News</a><a class="btn" href="https://www.eliteprospects.com/player/801209/mans-agren" target="_blank">EliteProspects</a><a class="btn" href="https://www.brooksbandits.net/" target="_blank">Brooks</a>`,'card wide')}${card('Senaste träffar',`<div class="list">${state.media.map(m=>`<div class="item"><span>${m}</span><span class="tag warn">kontrollera</span></div>`).join('')}</div>`)}</div>`}
function familj(){return `<div class="grid">${card('Familjekalender',`<textarea placeholder="Resor, matcher, påminnelser"></textarea><button class="btn gold">Spara</button>`)}${card('Packlistor',`<div class="list"><div class="item"><span>Pass/eTA/försäkring</span><span class="tag ok">viktigt</span></div><div class="item"><span>Matchresa</span><span class="tag">mall</span></div></div>`)}${card('Kontakter',`<input class="input" placeholder="Klubbkontakt, billet, agent"/><button class="btn">Lägg till</button>`)}</div>`}
function dokument(){return `<div class="grid">${card('Dokumentcenter',`<p class="muted">Lägg länkar till försäkringar, visum/eTA, avtal, resehandlingar och kvitton.</p><input class="input" placeholder="Dokumentnamn"/><input class="input" placeholder="Länk eller filplats"/><button class="btn gold">Spara dokument</button>`,'card wide')}${card('Viktiga dokument',`<div class="list"><div class="item"><span>BCHL försäkring</span><span class="tag warn">lägg till</span></div><div class="item"><span>Flygbokning</span><span class="tag warn">lägg till</span></div></div>`)}</div>`}
function karta(){return `<div class="grid">${card('Arenor och resor',`<p><b>Brooks:</b> Centennial Regional Arena</p><a class="btn gold" href="https://www.google.com/maps/search/?api=1&query=Centennial+Regional+Arena+Brooks" target="_blank">Öppna karta</a><a class="btn" href="https://www.google.com/maps/dir/Calgary+International+Airport/Centennial+Regional+Arena+Brooks" target="_blank">YYC → Brooks</a>`,'card full')}</div>`}
function ai(){return `<div class="grid">${card('AI-assistent',`<p class="muted">Fråga exempelvis: “När spelar Måns nästa match?”, “Sammanfatta senaste media”, “Vilka flyg är bäst?”</p><textarea placeholder="Skriv din fråga"></textarea><button class="btn gold">Fråga</button><p class="muted">Nästa steg: koppla till serverfunktion/AI-API.</p>`,'card wide')}${card('Snabbfrågor',`<button class="btn">Nästa match</button><button class="btn">Senaste media</button><button class="btn">Flyg under 10 000</button><button class="btn">Skapa matchrapport</button>`)}</div>`}
function admin(){return `<div class="grid">${card('Adminläge',`<p>Ändra nyckelvärden, länkar och manuella data utan att röra koden.</p><input class="input" value="${state.match.opponent}"/><input class="input" value="${state.match.arena}"/><button class="btn gold">Spara lokalt</button>`,'card wide')}${card('Datakällor',`<div class="list"><div class="item"><span>Weather API</span><span class="tag warn">nyckel krävs</span></div><div class="item"><span>Exchange rate API</span><span class="tag warn">nyckel/endpoint</span></div><div class="item"><span>Flight API</span><span class="tag warn">Amadeus/Kiwi</span></div><div class="item"><span>Media RSS</span><span class="tag ok">redo</span></div></div>`)}</div>`}
render();
