const teams={Brooks:{abbr:'BB',arena:'Centennial Regional Arena'},'Spruce Grove Saints':{abbr:'SG'},'Okotoks Oilers':{abbr:'OK'},'Blackfalds Bulldogs':{abbr:'BD'},'Sherwood Park Crusaders':{abbr:'SP'},'Cranbrook Bucks':{abbr:'CB'},'Vernon Vipers':{abbr:'VV'},'West Kelowna Warriors':{abbr:'WK'},'Trail Smoke Eaters':{abbr:'TR'},'Salmon Arm Silverbacks':{abbr:'SA'}};
const games=[
{d:'2026-09-09T03:00:00+02:00',home:true,opp:'Spruce Grove Saints',arena:'CRA',scout:'Försäsong'},
{d:'2026-09-12T03:05:00+02:00',home:false,opp:'Okotoks Oilers',arena:'Viking Rentals Centre',scout:'Försäsong'},
{d:'2026-09-13T03:00:00+02:00',home:true,opp:'Okotoks Oilers',arena:'CRA',scout:'Försäsong'},
{d:'2026-09-19T03:00:00+02:00',home:false,opp:'Blackfalds Bulldogs',arena:'Eagle Builders Centre',scout:'Hög'},
{d:'2026-09-20T03:00:00+02:00',home:true,opp:'Okotoks Oilers',arena:'CRA',scout:'Hög'},
{d:'2026-09-26T03:00:00+02:00',home:true,opp:'Spruce Grove Saints',arena:'CRA',scout:'Hög'},
{d:'2026-09-27T03:00:00+02:00',home:true,opp:'Sherwood Park Crusaders',arena:'CRA',scout:'Medel'},
{d:'2026-10-10T03:00:00+02:00',home:true,opp:'Alberni Valley Bulldogs',arena:'CRA',scout:'Showcase-läge'},
{d:'2026-10-18T03:00:00+02:00',home:true,opp:'Cowichan Valley Capitals',arena:'CRA',scout:'Medel'},
{d:'2026-10-24T03:00:00+02:00',home:true,opp:'Vernon Vipers',arena:'CRA',scout:'Hög'},
{d:'2026-10-25T03:00:00+02:00',home:false,opp:'Sherwood Park Crusaders',arena:'Sherwood Park Arena',scout:'Hög'},
{d:'2026-11-05T02:30:00+01:00',home:true,opp:'Trail Smoke Eaters',arena:'CRA',scout:'Medel'},
{d:'2026-11-21T03:00:00+01:00',home:true,opp:'Cranbrook Bucks',arena:'CRA',scout:'Hög'},
{d:'2026-12-20T04:00:00+01:00',home:true,opp:'Blackfalds Bulldogs',arena:'CRA',scout:'Hög'},
{d:'2027-01-02T00:00:00+01:00',home:true,opp:'Blackfalds Bulldogs',arena:'CRA',scout:'Hög'},
{d:'2027-01-03T03:00:00+01:00',home:true,opp:'Okotoks Oilers',arena:'CRA',scout:'Hög'},
{d:'2027-02-07T04:00:00+01:00',home:false,opp:'Sherwood Park Crusaders',arena:'Sherwood Park Arena',scout:'Hög'},
{d:'2027-03-21T03:00:00+01:00',home:true,opp:'Trail Smoke Eaters',arena:'CRA',scout:'Slutspelsjakt'}
];
const standings=[['Brooks Bandits',0,0,0,0],['Okotoks Oilers',0,0,0,0],['Blackfalds Bulldogs',0,0,0,0],['Spruce Grove Saints',0,0,0,0],['Sherwood Park Crusaders',0,0,0,0],['Cranbrook Bucks',0,0,0,0]];
const skills=[['Defensivt spel',92],['Boxplay',89],['Förstapass',86],['Fysik',88],['Pucktransport',76],['Spelförståelse',90]];
function fmt(d){return new Date(d).toLocaleString('sv-SE',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function nextGame(){const now=new Date();return games.find(g=>new Date(g.d)>now)||games[0]}
function countdown(date){let ms=Math.max(0,new Date(date)-new Date());let d=Math.floor(ms/864e5);ms%=864e5;let h=Math.floor(ms/36e5);ms%=36e5;let m=Math.floor(ms/6e4);return [d,h,m]}
function tab(name){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.getElementById(name).classList.add('active');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));window.scrollTo({top:0,behavior:'smooth'})}
const next=nextGame();
function render(){const [cd,ch,cm]=countdown(next.d);document.getElementById('app').innerHTML=`
<div class="wrap">
<section class="hero">
  <div><div class="badge">Brooks Bandits 2026/27 • Elite edition</div><h1 class="title">MansHockey<br>Elite</h1><p class="lead">Familjens hockeycentral med matchcenter, scoutlogg, BCHL-tabell, flygresor, mediabevakning, dokument, karta och AI-förberedda rapporter.</p><div class="actions"><button class="btn primary" onclick="tab('matches')">Visa matcher</button><button class="btn secondary" onclick="tab('ai')">AI-assistent</button></div></div>
  <div class="glass next"><div class="badge">Nästa match</div><h2>Brooks Bandits ${next.home?'vs':'@'} ${next.opp}</h2><p class="small">${fmt(next.d)} svensk tid • ${next.arena} • ${next.home?'Hemma':'Borta'}</p><div class="matchhero"><div><div class="logo">BB</div><b>Brooks</b></div><div class="vs">VS</div><div><div class="logo">${teams[next.opp]?.abbr||next.opp.slice(0,2)}</div><b>${next.opp}</b></div></div><div class="count"><div><strong>${cd}</strong><span>Dagar</span></div><div><strong>${ch}</strong><span>Tim</span></div><div><strong>${cm}</strong><span>Min</span></div><div><strong>03</strong><span>Svensk tid</span></div></div></div>
</section>
<div class="statsrow"><div class="glass stat"><small>Matcher</small><b>55</b></div><div class="glass stat"><small>Hemma</small><b>28</b></div><div class="glass stat"><small>Borta</small><b>27</b></div><div class="glass stat"><small>Brooks nu</small><b id="clock">--:--</b></div><div class="glass stat"><small>CAD/SEK</small><b>7.4</b></div></div>
<nav class="nav">${['home:Hem','matches:Matcher','player:Måns','standings:BCHL','matchcenter:Matchcenter','flights:Flyg','media:Media','scout:Scout','family:Familj','docs:Dokument','map:Karta','ai:AI'].map(x=>{let [id,t]=x.split(':');return `<button class="tab ${id==='home'?'active':''}" data-tab="${id}" onclick="tab('${id}')">${t}</button>`}).join('')}</nav>
${sections()}
</div>`;setInterval(()=>{let el=document.getElementById('clock'); if(el) el.textContent=new Date().toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit',timeZone:'America/Edmonton'})},1000)}
function cards(list=games.slice(0,8)){return list.map(g=>`<div class="card"><span class="pill ${g.home?'':'red'}">${g.home?'Hemma':'Borta'}</span><span class="pill">Scout: ${g.scout}</span><h3>Brooks Bandits ${g.home?'vs':'@'} ${g.opp}</h3><p class="small">${fmt(g.d)} svensk tid</p><p class="small">${g.arena}</p><button class="btn primary" onclick="tab('matchcenter')">Öppna matchcenter</button></div>`).join('')}
function sections(){return `
<section id="home" class="section active"><div class="topline"><h2>Översikt</h2><p class="small">Snabb koll inför nästa match.</p></div><div class="grid">${cards(games.slice(0,6))}</div></section>
<section id="matches" class="section"><div class="topline"><h2>Spelschema</h2><p class="small">Svensk tid, hemma/borta och scoutnivå.</p></div><div class="grid">${cards(games)}</div></section>
<section id="player" class="section"><div class="topline"><h2>Måns spelarprofil</h2></div><div class="profile"><div class="avatar"><div><div class="num">#</div><h2>Måns Ågren</h2><p class="small">Back • Left • 2006 • 185 cm • 93 kg</p></div></div><div class="card"><h3>Säsongsstatistik</h3><div class="statsrow" style="grid-template-columns:repeat(4,1fr)"><div><small>GP</small><b>0</b></div><div><small>G</small><b>0</b></div><div><small>A</small><b>0</b></div><div><small>+/-</small><b>0</b></div></div><div class="bars">${skills.map(s=>`<div class="bar"><label><span>${s[0]}</span><span>${s[1]}</span></label><div class="track"><div class="fill" style="width:${s[1]}%"></div></div></div>`).join('')}</div></div></div></section>
<section id="standings" class="section"><div class="topline"><h2>BCHL-tabell</h2><p class="small">Startläge. Uppdateras med resultat under säsongen.</p></div><div class="card"><table class="table"><thead><tr><th>Lag</th><th>GP</th><th>W</th><th>L</th><th>P</th></tr></thead><tbody>${standings.map(r=>`<tr class="${r[0]==='Brooks Bandits'?'highlight':''}"><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('')}</tbody></table></div></section>
<section id="matchcenter" class="section"><div class="topline"><h2>Matchcenter</h2><p class="small">Inför- och efterrapport.</p></div><div class="two"><div class="card"><div class="matchhero"><div><div class="logo">BB</div><b>Brooks</b></div><div class="vs">VS</div><div><div class="logo">${teams[next.opp]?.abbr||'OP'}</div><b>${next.opp}</b></div></div><h3>Inför match</h3><p class="note">Fokus: första passet ur zon, boxplay, fysisk närvaro framför mål och smarta byten mot motståndarens toppkedja.</p><ul class="small"><li>Arena: ${next.arena}</li><li>Scoutnivå: ${next.scout}</li><li>Väder och restid kan kopplas via API.</li></ul></div><div class="card"><h3>Efter match</h3><textarea placeholder="Skriv resultat, Måns insats, egna observationer och länkar till highlights..."></textarea><button class="btn primary">Spara matchanteckning</button></div></div></section>
<section id="flights" class="section"><div class="topline"><h2>Flygportal</h2><p class="small">ARN–YYC med Air Canada, KLM och Finnair.</p></div><div class="card"><div class="inputrow"><input value="ARN"><input value="YYC"><input type="date"><select><option>Air Canada, KLM, Finnair</option></select></div><div class="grid" style="margin-top:18px"><div class="card"><span class="pill green">Bästa val</span><h3>Air Canada</h3><p>ARN–YYC • 1 byte • ej USA</p><b>ca 8 900 kr</b></div><div class="card"><h3>KLM</h3><p>ARN–AMS–YYC</p><b>ca 9 400 kr</b></div><div class="card"><h3>Finnair</h3><p>ARN–HEL–YYC via partner</p><b>bevakas</b></div></div></div></section>
<section id="media" class="section"><div class="topline"><h2>Media Center</h2><p class="small">Sökningar: Måns Ågren, Brooks Bandits, BCHL, EliteProspects.</p></div><div class="grid"><div class="card"><span class="pill">Google News</span><h3>Nyheter om Måns</h3><p class="small">Daglig bevakning kan köras via Cloudflare Worker.</p></div><div class="card"><span class="pill">EliteProspects</span><h3>Profil & statistik</h3><p class="small">Direktlänk och manuell notering.</p></div><div class="card"><span class="pill">YouTube</span><h3>Highlights</h3><p class="small">Samla klipp per match.</p></div></div></section>
<section id="scout" class="section"><div class="topline"><h2>Scout Center</h2><p class="small">Egen scoutlogg och utvecklingskurvor.</p></div><div class="two"><div class="card"><h3>Bedömning</h3><div class="bars">${skills.map(s=>`<div class="bar"><label><span>${s[0]}</span><span>${s[1]}%</span></label><div class="track"><div class="fill" style="width:${s[1]}%"></div></div></div>`).join('')}</div></div><div class="card"><h3>Scoutanteckning</h3><textarea placeholder="Match, situationer, styrkor, förbättringar, clips..."></textarea><button class="btn primary">Spara</button></div></div></section>
<section id="family" class="section"><div class="topline"><h2>Familjeportal</h2></div><div class="grid"><div class="card"><h3>Packlistor</h3><p class="small">Resa, match, vinter, dokument.</p></div><div class="card"><h3>Kalender</h3><p class="small">Matcher, resor, lov och besök.</p></div><div class="card"><h3>Kontaktlista</h3><p class="small">Klubb, billet, försäkring, agent.</p></div><div class="card"><h3>Anteckningar</h3><p class="small">Familjens gemensamma noteringar.</p></div></div></section>
<section id="docs" class="section"><div class="topline"><h2>Dokumentcenter</h2></div><div class="grid"><div class="card"><h3>Pass & eTA</h3><p class="small">Spara checklistor och länkar.</p></div><div class="card"><h3>Försäkringar</h3><p class="small">BCHL, svensk försäkring, reseförsäkring.</p></div><div class="card"><h3>Kontrakt & klubbinfo</h3><p class="small">Brooks, boende och utrustning.</p></div></div></section>
<section id="map" class="section"><div class="topline"><h2>Karta & resor</h2></div><div class="two"><div class="card"><h3>Brooks</h3><p class="small">CRA, billet, gym, Calgary Airport och viktiga platser.</p></div><div class="card"><h3>Bortaresor</h3><div class="timeline">${games.filter(g=>!g.home).slice(0,5).map(g=>`<div class="event"><time>${fmt(g.d).split(',')[0]}</time><div>${g.opp}<br><span class="small">${g.arena}</span></div></div>`).join('')}</div></div></div></section>
<section id="ai" class="section"><div class="topline"><h2>AI-assistent</h2><p class="small">Förberedd yta för frågor om matcher, flyg, media och statistik.</p></div><div class="card"><textarea placeholder="Exempel: Hur ser nästa match ut? Har det skrivits något om Måns? Vilka flyg passar bäst till Calgary?"></textarea><button class="btn primary">Fråga AI</button><p class="small">Nästa steg: koppla till Cloudflare Worker + OpenAI/API.</p></div></section>
`}
render();
