import React,{useEffect,useRef,useState}from'react';
import{Brain,RefreshCw,TrendingUp,ShieldCheck,Crosshair,Activity,Home,Plane}from'lucide-react';
export function MatchIntelligence({match}){
 const[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const requestSeq=useRef(0),matchId=match?.id,opponent=match?.opponent||'';
 async function load(force=false){if(!matchId)return;const seq=++requestSeq.current;setLoading(true);setError('');setData(null);try{const r=await fetch(force?'/api/opponent-intel':`/api/opponent-intel?match_id=${encodeURIComponent(matchId)}`,{method:force?'POST':'GET',headers:force?{'content-type':'application/json'}:undefined,body:force?JSON.stringify({match_id:matchId}):undefined}),d=await r.json();if(seq!==requestSeq.current)return;if(!d.ok){setError(d.error||'Analysen kunde inte laddas.');return}const item=d.item;if(Number(item?.match_id)!==Number(matchId)||String(item?.opponent||'')!==String(opponent)){setError('Analysen matchade inte vald match.');return}setData(item)}catch(e){if(seq===requestSeq.current)setError(String(e))}finally{if(seq===requestSeq.current)setLoading(false)}}
 useEffect(()=>{requestSeq.current++;setData(null);setError('');if(matchId)load(false)},[matchId,opponent]);if(!matchId)return null;const a=data?.advanced||{};
 return <section className="intel-panel"><div className="intel-head"><div><span className="eyebrow">ADVANCED OPPONENT INTELLIGENCE</span><h3><Brain size={18}/> {opponent}</h3></div><button onClick={()=>load(true)} disabled={loading}><RefreshCw size={15}/>{loading?'Uppdaterar…':'Uppdatera'}</button></div>
 {loading&&<p>Hämtar analys för {opponent}…</p>}{!loading&&error&&<p>{error}</p>}{!loading&&!error&&!data&&<p>Analys saknas ännu.</p>}
 {!loading&&!error&&data&&<><p className="intel-summary">{data.ai_summary||data.form_summary}</p><div className="intel-grid">
 <article><strong><Activity size={15}/> Form 5</strong><p>{a.form5||'–'} · {a.record||'0-0'}</p></article><article><strong>GF / GA</strong><p>{a.gf??0} / {a.ga??0} · diff {a.diff>0?'+':''}{a.diff??0}</p></article><article><strong><Home size={15}/> Hemma</strong><p>{a.home_record||'0-0'}</p></article><article><strong><Plane size={15}/> Borta</strong><p>{a.away_record||'0-0'}</p></article><article><strong>Målsnitt</strong><p>{a.avg_for??0} framåt · {a.avg_against??0} bakåt</p></article><article><strong>Head-to-head</strong><p>{a.head_to_head_games??0} verifierade matcher</p></article><article><strong>Special Teams</strong><p>{a.special_teams?.note||'Data saknas'}</p></article><article><strong><ShieldCheck size={15}/> Datatillit</strong><p>{Math.round((data.confidence||0)*100)}%</p></article></div>
 <div className="intel-grid intel-actions"><article><strong><Crosshair size={16}/> Keys to the Game</strong>{(a.keys_to_game||[]).map((x,i)=><p key={i}>{i+1}. {x}</p>)}</article><article><strong><ShieldCheck size={16}/> Måns Focus</strong>{(a.mans_focus||[]).map((x,i)=><p key={i}>{i+1}. {x}</p>)}</article></div>
 {Array.isArray(data.last_games)&&data.last_games.length>0&&<div className="intel-games"><h4><TrendingUp size={16}/> Senaste verifierade matcher</h4>{data.last_games.map((g,i)=><div className="intel-game" key={i}><span>{new Date(g.date).toLocaleDateString('sv-SE')}</span><strong>{g.result}</strong><span>{g.outcome}</span></div>)}</div>}</>}</section>
}