CREATE TABLE IF NOT EXISTS scout_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, match_id TEXT, category TEXT, rating INTEGER, note TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS family_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, body TEXT, tag TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS media_hits (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, url TEXT, source TEXT, published_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS flight_alerts (id INTEGER PRIMARY KEY AUTOINCREMENT, route TEXT, max_price INTEGER, airlines TEXT, avoid_usa INTEGER DEFAULT 1, active INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
