import React,{useMemo,useState,useEffect}from'react';import{createRoot}from'react-dom/client';import{Plane,Newspaper,Trophy,User,CalendarDays,MapPin,CloudSun,Wallet,Shield,Video,FileText,Bell,Search}from'lucide-react';import'./styles.css';import{games,teams}from'./data/schedule';import{api}from'./lib/api';
const tabs=['Hem','Matchcenter','Live','Måns','Scout','Resor','Media','Familj','Admin','AI'];
function Countdown(){const next=games[0];const target=new Date(next.date+'T01:00:00Z').getTime();const[now,setNow]=useState(Date.now());useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);const d=Math.max(0,target-now);return <div className="count"><b>{Math.floor(d/86400000)}</b><span>dagar</span><b>{Math.floor(d/3600000)%24}</b><span>tim</span><b>{Math.floor(d/60000)%60}</b><span>min</span></div>}
function Card(p:{children:React.ReactNode,className?:string}){return <section className={'card '+(p.className||'')}>{p.children}</section>}
function Home(){return <><div className="hero"><div><p className="kicker">BROOKS BANDITS 2026/27</p><h1>MansHockey 3.0</h1><p className="lead">Professionell familjeapp med matchcenter, live-data, scoutlogg, resecenter, mediabevakning och AI-stöd.</p><div className="actions"><a href="/mans_bchl_2026_27_calendar.ics">Ladda ner kalender</a><button onClick={()=>document.querySelector('#schedule')?.scrollIntoView({behavior:'smooth'})}>Visa matcher</button></div></div><Card className="next"><p className="kicker">Nästa match</p><h2>Brooks Bandits vs {games[0].opponent}</h2><p>{games[0].date} kl. {games[0].swedishTime} svensk tid • {games[0].arena}</p><Countdown/></Card></div><div className="livegrid"><Card><CloudSun/> <span>Brooks väder</span><b>hämtas via API</b></Card><Card><Wallet/><span>CAD/SEK</span><b>hämtas via API</b></Card><Card><Newspaper/><span>Media</span><b>”Måns Ågren”</b></Card><Card><Trophy/><span>BCHL</span><b>Tabell & resultat</b></Card></div><h2 id="schedule">Snabböversikt</h2><div className="grid">{games.map(g=><Card key={g.id}><span className="pill">{g.home?'Hemma':'Borta'}</span><span className="pill">Scout: {g.scout}</span><h3>Brooks {g.home?'vs':'@'} {g.opponent}</h3><p>{g.date} • {g.swedishTime} svensk tid</p><p>{g.arena}</p></Card>)}</div></>}
function Matchcenter(){return <><h2>Matchcenter</h2><div className="grid">{games.map(g=><Card key={g.id}><h3>Brooks {g.home?'vs':'@'} {g.opponent}</h3><p><CalendarDays/> {g.date} {g.swedishTime} svensk tid</p><p><MapPin/> {g.arena}</p><div className="report"><b>Inför:</b> form, nyckelspelare, special teams, scoutfokus och väder.</div><div className="report"><b>Efter:</b> resultat, AI-matchrapport, Måns statistik, highlights och bilder.</div></Card>)}</div></>}
function Live(){return <><h2>Livecenter</h2><Card><h3>BCHL-tabell</h3><table><tbody>{teams.map(t=><tr key={t[0]}><td>{t[0]}</td><td>GP {t[1]}</td><td>W {t[2]}</td><td>L {t[3]}</td><td>P {t[4]}</td></tr>)}</tbody></table></Card><div className="grid"><Card><h3>Resultat</h3><p>Här kopplas BCHL-resultat in via API/cache.</p></Card><Card><h3>Form senaste 5</h3><p>Automatisk formrad när resultat finns.</p></Card></div></>}
function Mans(){return <><h2>Måns Ågren</h2><div className="profile"><Card><User/><h3>Back • Left • 2006</h3><p>185 cm • 93 kg • Brooks Bandits</p></Card><Card><h3>Säsongsstatistik</h3><div className="stats"><b>0</b><span>M</span><b>0</b><span>A</span><b>0</b><span>P</span><b>0</b><span>+/-</span></div></Card></div></>}
function Scout(){return <><h2>Scout Center</h2>{['Defensiv','Förstapass','Fysik','Pucktransport','Spelförståelse'].map((x,i)=><Card key={x}><h3>{x}</h3><div className="bar"><i style={{width:`${80-i*7}%`}}/></div><p>Efter varje match kan betyg och anteckningar sparas i D1.</p></Card>)}</>}
function Flights(){return <><h2>Resecenter</h2><Card><Plane/><h3>ARN → YYC</h3><p>Air Canada, KLM och Finnair. Filter: ingen USA-transit, avgång efter 09:30, kort restid och maxpris.</p><button>Spara bevakning</button></Card><div className="grid"><Card><h3>Air Canada</h3><p>Pris hämtas via flyg-API</p></Card><Card><h3>KLM</h3><p>Pris hämtas via flyg-API</p></Card><Card><h3>Finnair</h3><p>Pris hämtas via flyg-API</p></Card></div></>}
function Media(){return <><h2>Media</h2><Card><Search/><h3>Automatisk bevakning</h3><p>”Måns Ågren”, ”Mans Agren”, Brooks Bandits, BCHL och EliteProspects.</p></Card><div className="grid"><Card><Newspaper/><h3>Google News</h3><p>Senaste träffar visas här.</p></Card><Card><Video/><h3>YouTube</h3><p>Highlights och klipp samlas per match.</p></Card></div></>}
function Family(){return <><h2>Familjeportal</h2><div className="grid">{['Dokument','Packlistor','Flygbokningar','Boenden','Försäkringar','Kvitton'].map(x=><Card key={x}><FileText/><h3>{x}</h3><p>Privat innehåll för familjen. Förberett för inloggning.</p></Card>)}</div></>}
function Admin(){return <><h2>Admin</h2><Card><Shield/><h3>Inloggningsförberett</h3><p>Adminläge för matcher, scoutbetyg, länkar, media, resor och dokument. Kopplas till Cloudflare Access eller Supabase Auth.</p></Card></>}
function AI(){return <><h2>AI-assistent</h2><Card><h3>Fråga appen</h3><textarea placeholder="Ex: Hur har Måns spelat senaste fem matcherna?"/><button>Skapa svar</button><p>AI-koppling kan läggas via Cloudflare Worker.</p></Card></>}
function App(){const[tab,setTab]=useState('Hem');const Page={Hem:Home,Matchcenter,Live,Måns:Mans,Scout,Resor:Flights,Media,Familj:Family,Admin,AI}[tab]||Home;return <main><header><div className="brand">MÅ</div><b>MansHockey</b><span>Elite player & family platform</span></header><nav>{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav><Page/><footer>manshockey.com • Brooks Bandits 2026/27 • PWA + Cloudflare</footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);
